# Generated by Django 5.0.3 on 2026-05-05 19:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Display",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "parameter",
                    models.CharField(max_length=512, verbose_name="Display parameter"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OperationSystem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=256, verbose_name="OS name")),
            ],
        ),
        migrations.CreateModel(
            name="Processor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "generation",
                    models.CharField(
                        max_length=512, verbose_name="Generation of the processor"
                    ),
                ),
                ("core", models.CharField(max_length=256, verbose_name="Processor")),
            ],
        ),
        migrations.CreateModel(
            name="RamMemory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "capacity",
                    models.CharField(max_length=256, verbose_name="RAM capacity"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StorageMemory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "capacity",
                    models.CharField(max_length=256, verbose_name="Storage capacity"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Laptop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=1024, verbose_name="Model name")),
                ("price", models.IntegerField(verbose_name="Price(₹)")),
                (
                    "rating",
                    models.FloatField(blank=True, null=True, verbose_name="Rating"),
                ),
                ("warranty", models.IntegerField(verbose_name="Warranty (In Years)")),
                (
                    "display",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="recommender.display",
                    ),
                ),
                (
                    "os",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="recommender.operationsystem",
                    ),
                ),
                (
                    "processor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="recommender.processor",
                    ),
                ),
                (
                    "ram",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="recommender.rammemory",
                    ),
                ),
                (
                    "storage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="recommender.storagememory",
                    ),
                ),
            ],
        ),
    ]
